#!/usr/bin/env bash

#
# Script for deploying a Canvas release to a Canvas application
# or management server
#
# Usage:
#  ./deploy.sh -r <release-name> [-f]
#
# Arguments:
#   <release-name>: typically generated by Bamboo, determines
#                   where the release will be installed
#

set -e
set -u
set -o pipefail

# Default options
FORCE=false
RELEASE_TARBALL=
CANVAS_ROOT=/var/rails/canvas/releases
CANVAS_ENV=
RELEASE=
INSTALL_DIR=
TARBALL=canvas.tar
ID=$(id -u canvasuser)
IS_PRIMARY_MANAGEMENT_NODE=false

usage () {
  echo "usage: $(basename "$0") -e <environment> -r <path> [-f]"
  echo -e "\nDeploys a Canvas release to an application or management server."
  echo -e "\nOptions:"
  echo -e "    -r <path>    The target installation path. Path must not already exist unless using -f"
  echo -e "    -f           Force installation to the target path. Target will be removed and replaced."
  echo -e "    -h           Show this help, then exit\n"
}

is_primary_managmeent_node() {
  # determine if a node is the primary managment node from its hostname
  # the primary node is the one with 01 in the hostname
  local short_node
  short_node=$(hostname -s | sed -e 's/lcp-canvas-//')
  local node_type=${short_node:0:1}
  local node_num=${short_node:2}
  if [ "$node_type" = "m" -a "$node_num" = "01" ]; then
    IS_PRIMARY_MANAGEMENT_NODE=true
  fi
}

run_on_primary_management_node() {
  if [ $IS_PRIMARY_MANAGEMENT_NODE = true ] ; then
    $1
  fi
}


getenv() {
  # determine the environment from the hostname
  shortenv=$(hostname -s | sed -e 's/lcp-canvas-[am]//' | sed -e 's/[0-9]\+//')
  case "$shortenv" in
    p)
      CANVAS_ENV="production"
    ;;
    s)
      CANVAS_ENV="stage"
    ;;
    t)
      CANVAS_ENV="test"
    ;;
    *)
      echo "ERROR: could not determine Canvas environment from hostname. Are you running on a Canvas server?"
      exit 1
  esac
}

preflight() {
  getenv
  # check if the release exists
  echo "Performing preflight checks"
  printf "Release tarball exists? "
  if [ -f "/usr/local/canvas/deploy-release-$CANVAS_ENV/$RELEASE/canvas.tar" ]; then
    printf "yes\n"
  else
    printf "no\n"
    echo "Aborting - no release tarball."
    exit 1
  fi
  
  # check if release directory exists; bail if true && !FORCE
  printf "Release directory exists? "
  if [ -d "$CANVAS_ROOT"/"$RELEASE" ] ; then
    if [ ! $FORCE ] ; then
      printf "yes\n"
      echo "Aborting - release directory already exists"
      exit 1
    else
      printf "yes - but using force mode"
    fi
  else
    printf "no\n"
  fi

  echo "Preflight checks complete, proceeding"
}

create_release_dir() {
  echo "hi"
}

while getopts ':fhr:' OPTION ; do
  case "$OPTION" in
    f)
      FORCE=true
    ;;
    h)
      usage
      exit 0
    ;;
    r)
      if [ -z "$OPTARG" ] ; then
        usage
        exit 1
      fi
      RELEASE="$OPTARG"
    ;;
    ?)
      usage
      exit 1
    ;;
  esac
done

if [ -z "$RELEASE" ] ; then
  usage
  exit 1
fi

# echo "Deploying Canvas release to $CANVAS_ROOT/$RELEASE"

preflight